version: '3'
services:
  node_alice:
    build:
      context: .
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    image: chevdor/polkadot:latest
    volumes:
      - "polkadot-data-alice:/data"
    command: polkadot --chain=polkadot-local --alice -d /data --node-key 0000000000000000000000000000000000000000000000000000000000000001
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  node_bob:
    build:
      context: .
    ports:
      - "30344:30344"
      - "9935:9935"
      - "9945:9945"
    image: chevdor/polkadot:latest
    volumes:
      - "polkadot-data-bob:/data"
    links:
      - "node_alice:alice"
    command: polkadot --chain=polkadot-local --bob -d /data --port 30344 --rpc-port 9935 --ws-port 9945 --bootnodes '/ip4/172.28.1.1/tcp/30333/p2p/QmRpheLN4JWdAnY7HGJfWFNbfkQCb6tFf4vvA6hgjMZKrR'
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  etherum:
    build:
      context: .
    ports:
      - "8545:8545"
    image: test/etherum:latest
    command: "./docker/start_ganache.sh& ./docker/wait-for -t 32 127.0.0.1:8545 -- ./docker/deploy_contracts.sh && ./docker/restart_ganache.sh"
    network:
      testing_net:
        ipv4_address: 172.28.1.3

volumes:
  polkadot-data-alice:
  polkadot-data-bob:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
