version: '3'
services:
  node_alice:
    build:
      context: .
    ports:
      - "30444:30444"
      - "9933:9933"
      - "9944:9944"
    image: efinity/polkadot-nc:latest
    volumes:
      - "parachainvol:/data"
    command: ["nc -v -l -p 1234 && polkadot --chain=/data/rococo-local-raw.json --rpc-methods=unsafe --tmp --alice --port 30444 --rpc-external --ws-external --rpc-cors all --rpc-port 9933 --ws-port 9944 --enable-offchain-indexing=true --offchain-worker=Always"]
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  node_bob:
    build:
      context: .
    ports:
      - "30555:30555"
      - "9935:9935"
      - "9955:9955"
    image: efinity/polkadot-nc:latest
    volumes:
      - "parachainvol:/data"
    command: ["nc -v -l -p 1234 && polkadot --chain=/data/rococo-local-raw.json --tmp --bob --port 30555 --rpc-external --ws-external --rpc-port 9935 --ws-port 9955 --enable-offchain-indexing=true --offchain-worker=Always"]
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  node_charlie:
    build:
      context: .
    ports:
      - "30777:30777"
      - "9939:9939"
      - "9966:9966"
    image: efinity/polkadot-nc:latest
    volumes:
      - "parachainvol:/data"
    command: ["nc -v -l -p 1234 && polkadot --chain=/data/rococo-local-raw.json --tmp --charlie --port 30777 --rpc-external --ws-external --rpc-port 9939 --ws-port 9966 --enable-offchain-indexing=true --offchain-worker=Always"]
    networks:
      testing_net:
        ipv4_address: 172.28.1.8

  node_parachain:
    build:
      context: ../parachain
    ports:
      - "31200:31200"
      - "9937:9937"
      - "11144:11144"
    image: efinity/artemis:latest
    volumes:
      - "parachainvol:/data"
    command: ['nc -v -l -p 1234 && ls /data/ && /usr/local/bin/artemis --tmp --alice --rpc-methods=unsafe --ws-port=11144 --port=31200 --rpc-external --ws-external --rpc-port 9937 --execution=native --offchain-worker=Always --enable-offchain-indexing=true --rpc-cors all --parachain-id=200 --chain=/data/spec.json --collator --force-authoring -- --chain=/data/rococo-local-raw.json --rpc-cors all --ws-external --rpc-external --execution=wasm']
    networks:
      testing_net:
        ipv4_address: 172.28.1.3


  relayer:
    build:
      context: ../relayer
    image: efinity/artemis-relayer:latest
    command: /bin/sh -c 'sleep 180 && /usr/local/bin/artemis-relay run --config config.toml'
    entrypoint: ""
    environment:
      - BEEFY_RELAYER_ETHEREUM_KEY=0x935b65c833ced92c43ef9de6bff30703d941bd92a2637cb00cfad389f5862109
      - PARACHAIN_COMMITMENT_RELAYER_ETHEREUM_KEY=0x8013383de6e5a891e7754ae1ef5a21e7661f1fe67cd47ca8ebf4acd6de66879a
      - ARTEMIS_PARACHAIN_KEY=//Relay
      - ARTEMIS_RELAYCHAIN_KEY=//Alice
    networks:
      testing_net:
        ipv4_address: 172.28.1.7

  etherum:
    build:
      context: ../ethereum
    ports:
      - "8545:8545"
    volumes:
      - "parachainvol:/data"
    image: efinity/artemis-etherum:latest
    command: ['./start_ganache.sh& ./wait-for -t 32 127.0.0.1:8545 -- ./deploy_contracts.sh && pkill node && echo 1 | nc -q 0 172.28.1.5 1234 && ./restart_ganache.sh']
    networks:
      testing_net:
        ipv4_address: 172.28.1.4

  parachain_spec:
    build:
      context: ../parachain
    volumes:
      - "parachainvol:/data"
    image : efinity/artemis:latest
    command: /bin/bash -c 'nc -l -v -p 1234 && ./wait-for.sh -t 32 172.28.1.4:8545 -- ./create_parachain_spec.sh && cp ./spec.json /data/spec.json && echo 1 | nc -q 0 172.28.1.6 1234'
    entrypoint: ""
    networks:
      testing_net:
        ipv4_address: 172.28.1.5

  build_spec:
    build:
      context: .
    volumes:
      - "parachainvol:/data"
    image : efinity/polkadot-nc:latest
    command: ['nc -l -v -p 1234 && ./create_spec.sh && cp rococo-local-raw.json /data/rococo-local-raw.json && echo 1 | nc -q 0 172.28.1.1 1234 && echo 1 | nc -q 0 172.28.1.2 1234 && echo 1 | nc -q 0 172.28.1.3 1234 && echo 1 | nc -q 0 172.28.1.8 1234']
    networks:
      testing_net:
        ipv4_address: 172.28.1.6

volumes:
  parachainvol:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
