[ethereum]
endpoint = "ws://etherum:8545/"
startblock = 1
descendants-until-final = 3
beefylightclient = "0x83428c7db9815f482a39a1715684dCF755021997"

[ethereum.channels.basic]
inbound = "0xEE9170ABFbf9421Ad6DD07F6BDec9D89F2B581E0"
outbound = "0xB1185EDE04202fE62D38F5db72F71e38Ff3E8305"

[ethereum.channels.incentivized]
inbound = "0xB8EA8cB425d85536b158d661da1ef0895Bb92F1D"
outbound = "0x8cF6147918A5CBb672703F879f385036f8793a24"

[parachain]
endpoint = "ws://node_parachain:11144/"

[relaychain]
endpoint = "ws://node_alice:9944/"

[database]
dialect = "sqlite3"
dbpath = "tmp.db"

[workers.parachaincommitmentrelayer]
enabled = true
restart-delay = 30

[workers.beefyrelayer]
enabled = true
restart-delay = 30

[workers.ethrelayer]
enabled = true
restart-delay = 30
